name: Create and publish the coin's containers
on: push
jobs:
  build_coins:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and run tests
        run: docker build -t hydra:latest . && docker run --entrypoint=make hydra:latest check