name: Create and publish the coin's containers
on: push
jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push latest
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: hydra:latest
      -
        name: Execute tests
        run: docker run --entrypoint=make hydra:latest check